use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum UiActionId {
    AbortExecution,
    NewSession,
    OpenSessionList,
    NavigateParentSession,
    OpenRecoveryList,
    ShareSession,
    UnshareSession,
    RenameSession,
    ForkSession,
    CompactSession,
    Timeline,
    Undo,
    Redo,
    CopySession,
    ExportSession,
    OpenModelList,
    OpenModeList,
    OpenAgentList,
    OpenPresetList,
    OpenMcpList,
    ConnectProvider,
    OpenThemeList,
    ShowStatus,
    ShowHelp,
    ExternalEditor,
    Exit,
    ToggleTimestamps,
    ToggleTips,
    ToggleThinking,
    ToggleToolDetails,
    ToggleDensity,
    ToggleSemanticHighlight,
    ToggleSidebar,
    ToggleHeader,
    ToggleScrollbar,
    ToggleCommandPalette,
    OpenStash,
    OpenSkills,
    ListTasks,
    SubmitPrompt,
    ClearPrompt,
    PasteClipboard,
    CopyPrompt,
    CutPrompt,
    HistoryPrevious,
    HistoryNext,
    PromptStashPush,
    PromptStashList,
    PromptSkillList,
    CycleVariant,
    ToggleAppearance,
    ViewStatus,
    ToggleMcp,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum UiCommandCategory {
    Session,
    ModelAgent,
    Display,
    Navigation,
    System,
    Prompt,
    Help,
    App,
    View,
}

impl UiCommandCategory {
    pub fn label(self) -> &'static str {
        match self {
            Self::Session => "Session",
            Self::ModelAgent => "Model & Agent",
            Self::Display => "Display",
            Self::Navigation => "Navigation",
            Self::System => "System",
            Self::Prompt => "Prompt",
            Self::Help => "Help",
            Self::App => "App",
            Self::View => "View",
        }
    }
}

#[derive(Debug, Clone, Serialize)]
pub struct UiSlashCommandSpec {
    pub name: &'static str,
    pub aliases: &'static [&'static str],
    pub suggested: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum UiCommandArgumentKind {
    None,
    SessionTarget,
    ModelRef,
    ThemeId,
    ModeRef,
    AgentRef,
    PresetRef,
}

#[derive(Debug, Clone, Serialize)]
pub struct UiCommandSpec {
    pub action_id: UiActionId,
    pub title: &'static str,
    pub description: &'static str,
    pub category: UiCommandCategory,
    pub keybind: Option<&'static str>,
    pub include_in_palette: bool,
    pub slash: Option<UiSlashCommandSpec>,
}

impl UiCommandSpec {
    pub fn argument_kind(&self) -> UiCommandArgumentKind {
        ui_command_argument_kind(self.action_id)
    }
}

pub fn ui_command_argument_kind(action_id: UiActionId) -> UiCommandArgumentKind {
    match action_id {
        UiActionId::OpenSessionList => UiCommandArgumentKind::SessionTarget,
        UiActionId::OpenModelList => UiCommandArgumentKind::ModelRef,
        UiActionId::OpenModeList => UiCommandArgumentKind::ModeRef,
        UiActionId::OpenAgentList => UiCommandArgumentKind::AgentRef,
        UiActionId::OpenPresetList => UiCommandArgumentKind::PresetRef,
        UiActionId::OpenThemeList => UiCommandArgumentKind::ThemeId,
        _ => UiCommandArgumentKind::None,
    }
}

pub fn builtin_ui_commands() -> Vec<UiCommandSpec> {
    vec![
        UiCommandSpec {
            action_id: UiActionId::AbortExecution,
            title: "Abort Execution",
            description: "Cancel the active run or scheduler stage",
            category: UiCommandCategory::Session,
            keybind: None,
            include_in_palette: false,
            slash: Some(UiSlashCommandSpec {
                name: "/abort",
                aliases: &[],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::NewSession,
            title: "New Session",
            description: "Start a new conversation",
            category: UiCommandCategory::Session,
            keybind: Some("ctrl+n"),
            include_in_palette: true,
            slash: Some(UiSlashCommandSpec {
                name: "/new",
                aliases: &["/clear"],
                suggested: true,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::OpenSessionList,
            title: "Switch Session",
            description: "Switch to another session",
            category: UiCommandCategory::Session,
            keybind: Some("ctrl+s"),
            include_in_palette: true,
            slash: Some(UiSlashCommandSpec {
                name: "/sessions",
                aliases: &["/session", "/resume", "/continue"],
                suggested: true,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::NavigateParentSession,
            title: "Parent Session",
            description: "Return to the parent session or main view",
            category: UiCommandCategory::Session,
            keybind: Some("alt+left"),
            include_in_palette: true,
            slash: Some(UiSlashCommandSpec {
                name: "/parent",
                aliases: &["/back"],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::OpenRecoveryList,
            title: "Recovery Actions",
            description: "Open recovery actions for the current session",
            category: UiCommandCategory::Session,
            keybind: None,
            include_in_palette: false,
            slash: Some(UiSlashCommandSpec {
                name: "/recover",
                aliases: &["/recovery"],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::ShareSession,
            title: "Share Session",
            description: "Generate a shareable link",
            category: UiCommandCategory::Session,
            keybind: None,
            include_in_palette: false,
            slash: Some(UiSlashCommandSpec {
                name: "/share",
                aliases: &[],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::UnshareSession,
            title: "Unshare Session",
            description: "Revoke sharing link",
            category: UiCommandCategory::Session,
            keybind: None,
            include_in_palette: false,
            slash: Some(UiSlashCommandSpec {
                name: "/unshare",
                aliases: &[],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::RenameSession,
            title: "Rename Session",
            description: "Rename current session",
            category: UiCommandCategory::Session,
            keybind: None,
            include_in_palette: true,
            slash: Some(UiSlashCommandSpec {
                name: "/rename",
                aliases: &[],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::ForkSession,
            title: "Fork Session",
            description: "Create a fork from a message",
            category: UiCommandCategory::Session,
            keybind: None,
            include_in_palette: false,
            slash: Some(UiSlashCommandSpec {
                name: "/fork",
                aliases: &[],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::CompactSession,
            title: "Compact Session",
            description: "Summarize and compress session history",
            category: UiCommandCategory::Session,
            keybind: None,
            include_in_palette: false,
            slash: Some(UiSlashCommandSpec {
                name: "/compact",
                aliases: &["/summarize"],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::Timeline,
            title: "Timeline",
            description: "Navigate to a message in timeline",
            category: UiCommandCategory::Session,
            keybind: None,
            include_in_palette: false,
            slash: Some(UiSlashCommandSpec {
                name: "/timeline",
                aliases: &[],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::Undo,
            title: "Undo",
            description: "Revert last message",
            category: UiCommandCategory::Session,
            keybind: None,
            include_in_palette: false,
            slash: Some(UiSlashCommandSpec {
                name: "/undo",
                aliases: &[],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::Redo,
            title: "Redo",
            description: "Restore reverted message",
            category: UiCommandCategory::Session,
            keybind: None,
            include_in_palette: false,
            slash: Some(UiSlashCommandSpec {
                name: "/redo",
                aliases: &[],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::CopySession,
            title: "Copy Session",
            description: "Copy session to clipboard",
            category: UiCommandCategory::Session,
            keybind: None,
            include_in_palette: false,
            slash: Some(UiSlashCommandSpec {
                name: "/copy",
                aliases: &[],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::ExportSession,
            title: "Export Session",
            description: "Export session as markdown",
            category: UiCommandCategory::Session,
            keybind: None,
            include_in_palette: true,
            slash: Some(UiSlashCommandSpec {
                name: "/export",
                aliases: &[],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::OpenModelList,
            title: "Switch Model",
            description: "Choose a different model",
            category: UiCommandCategory::ModelAgent,
            keybind: Some("ctrl+m"),
            include_in_palette: true,
            slash: Some(UiSlashCommandSpec {
                name: "/models",
                aliases: &["/model"],
                suggested: true,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::OpenModeList,
            title: "Switch Mode",
            description: "Choose a different execution mode",
            category: UiCommandCategory::ModelAgent,
            keybind: None,
            include_in_palette: true,
            slash: Some(UiSlashCommandSpec {
                name: "/mode",
                aliases: &[],
                suggested: true,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::OpenAgentList,
            title: "Switch Agent",
            description: "Choose a different agent",
            category: UiCommandCategory::ModelAgent,
            keybind: None,
            include_in_palette: true,
            slash: Some(UiSlashCommandSpec {
                name: "/agent",
                aliases: &["/agents"],
                suggested: true,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::OpenPresetList,
            title: "Switch Preset",
            description: "Choose a different preset or profile",
            category: UiCommandCategory::ModelAgent,
            keybind: None,
            include_in_palette: true,
            slash: Some(UiSlashCommandSpec {
                name: "/preset",
                aliases: &["/presets"],
                suggested: true,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::OpenMcpList,
            title: "Manage MCP",
            description: "Manage MCP servers",
            category: UiCommandCategory::ModelAgent,
            keybind: None,
            include_in_palette: false,
            slash: Some(UiSlashCommandSpec {
                name: "/mcps",
                aliases: &[],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::ConnectProvider,
            title: "Connect Provider",
            description: "Connect to a new LLM provider",
            category: UiCommandCategory::ModelAgent,
            keybind: None,
            include_in_palette: false,
            slash: Some(UiSlashCommandSpec {
                name: "/connect",
                aliases: &[],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::OpenThemeList,
            title: "Switch Theme",
            description: "Choose a color theme",
            category: UiCommandCategory::Display,
            keybind: Some("ctrl+t"),
            include_in_palette: true,
            slash: Some(UiSlashCommandSpec {
                name: "/themes",
                aliases: &["/theme"],
                suggested: true,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::ShowStatus,
            title: "Status",
            description: "Show system status",
            category: UiCommandCategory::System,
            keybind: None,
            include_in_palette: true,
            slash: Some(UiSlashCommandSpec {
                name: "/status",
                aliases: &["/stats"],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::ShowHelp,
            title: "Help",
            description: "Show help and shortcuts",
            category: UiCommandCategory::System,
            keybind: Some("f1"),
            include_in_palette: true,
            slash: Some(UiSlashCommandSpec {
                name: "/help",
                aliases: &["/commands"],
                suggested: true,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::ExternalEditor,
            title: "External Editor",
            description: "Open in external editor",
            category: UiCommandCategory::System,
            keybind: None,
            include_in_palette: false,
            slash: Some(UiSlashCommandSpec {
                name: "/editor",
                aliases: &[],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::Exit,
            title: "Exit",
            description: "Exit the application",
            category: UiCommandCategory::System,
            keybind: Some("ctrl+c"),
            include_in_palette: true,
            slash: Some(UiSlashCommandSpec {
                name: "/exit",
                aliases: &["/quit", "/q"],
                suggested: true,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::ToggleTimestamps,
            title: "Toggle Timestamps",
            description: "Show/hide message timestamps",
            category: UiCommandCategory::Display,
            keybind: None,
            include_in_palette: false,
            slash: Some(UiSlashCommandSpec {
                name: "/timestamps",
                aliases: &["/toggle-timestamps"],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::ToggleTips,
            title: "Toggle Tips",
            description: "Show/hide home page tips",
            category: UiCommandCategory::Display,
            keybind: None,
            include_in_palette: true,
            slash: Some(UiSlashCommandSpec {
                name: "/tips.toggle",
                aliases: &["/tips"],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::ToggleThinking,
            title: "Toggle Thinking",
            description: "Show/hide thinking blocks",
            category: UiCommandCategory::Display,
            keybind: None,
            include_in_palette: true,
            slash: Some(UiSlashCommandSpec {
                name: "/thinking",
                aliases: &["/toggle-thinking"],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::ToggleToolDetails,
            title: "Toggle Tool Details",
            description: "Show/hide expanded tool details",
            category: UiCommandCategory::Display,
            keybind: Some("ctrl+o"),
            include_in_palette: true,
            slash: None,
        },
        UiCommandSpec {
            action_id: UiActionId::ToggleDensity,
            title: "Toggle Density",
            description: "Switch between compact and cozy message layout",
            category: UiCommandCategory::Display,
            keybind: None,
            include_in_palette: true,
            slash: Some(UiSlashCommandSpec {
                name: "/density",
                aliases: &["/toggle-density"],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::ToggleSemanticHighlight,
            title: "Toggle Semantic Highlight",
            description: "Enable/disable semantic highlighting of paths, errors, and commands",
            category: UiCommandCategory::Display,
            keybind: None,
            include_in_palette: true,
            slash: Some(UiSlashCommandSpec {
                name: "/highlight",
                aliases: &["/toggle-highlight", "/semantic"],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::ToggleSidebar,
            title: "Toggle Sidebar",
            description: "Show/hide sidebar",
            category: UiCommandCategory::Display,
            keybind: Some("ctrl+b"),
            include_in_palette: true,
            slash: Some(UiSlashCommandSpec {
                name: "/sidebar",
                aliases: &[],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::ToggleHeader,
            title: "Toggle Header",
            description: "Show/hide session header",
            category: UiCommandCategory::Display,
            keybind: None,
            include_in_palette: true,
            slash: Some(UiSlashCommandSpec {
                name: "/header",
                aliases: &[],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::ToggleScrollbar,
            title: "Toggle Scrollbar",
            description: "Show/hide session scrollbar",
            category: UiCommandCategory::Display,
            keybind: None,
            include_in_palette: true,
            slash: Some(UiSlashCommandSpec {
                name: "/scrollbar",
                aliases: &[],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::ToggleCommandPalette,
            title: "Command Palette",
            description: "Open command palette",
            category: UiCommandCategory::Navigation,
            keybind: Some("ctrl+p"),
            include_in_palette: false,
            slash: Some(UiSlashCommandSpec {
                name: "/command",
                aliases: &["/cmd", "/palette"],
                suggested: true,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::OpenStash,
            title: "Prompt Stash",
            description: "Save current prompt to stash",
            category: UiCommandCategory::Prompt,
            keybind: None,
            include_in_palette: false,
            slash: Some(UiSlashCommandSpec {
                name: "/stash",
                aliases: &[],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::OpenSkills,
            title: "Skills",
            description: "Browse available skills",
            category: UiCommandCategory::Navigation,
            keybind: None,
            include_in_palette: false,
            slash: Some(UiSlashCommandSpec {
                name: "/skills",
                aliases: &[],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::ListTasks,
            title: "Agent Tasks",
            description: "List, inspect, and cancel agent tasks",
            category: UiCommandCategory::System,
            keybind: None,
            include_in_palette: false,
            slash: Some(UiSlashCommandSpec {
                name: "/tasks",
                aliases: &["/task"],
                suggested: false,
            }),
        },
        UiCommandSpec {
            action_id: UiActionId::SubmitPrompt,
            title: "Submit prompt",
            description: "Submit the current prompt",
            category: UiCommandCategory::Prompt,
            keybind: Some("enter"),
            include_in_palette: true,
            slash: None,
        },
        UiCommandSpec {
            action_id: UiActionId::ClearPrompt,
            title: "Clear prompt",
            description: "Clear the current prompt input",
            category: UiCommandCategory::Prompt,
            keybind: Some("ctrl+u"),
            include_in_palette: true,
            slash: None,
        },
        UiCommandSpec {
            action_id: UiActionId::PasteClipboard,
            title: "Paste from clipboard",
            description: "Paste clipboard content into the prompt",
            category: UiCommandCategory::Prompt,
            keybind: Some("ctrl+v"),
            include_in_palette: true,
            slash: None,
        },
        UiCommandSpec {
            action_id: UiActionId::CopyPrompt,
            title: "Copy prompt to clipboard",
            description: "Copy the current prompt to clipboard",
            category: UiCommandCategory::Prompt,
            keybind: Some("ctrl+shift+c"),
            include_in_palette: true,
            slash: None,
        },
        UiCommandSpec {
            action_id: UiActionId::CutPrompt,
            title: "Cut prompt to clipboard",
            description: "Cut the current prompt to clipboard",
            category: UiCommandCategory::Prompt,
            keybind: Some("ctrl+shift+x"),
            include_in_palette: true,
            slash: None,
        },
        UiCommandSpec {
            action_id: UiActionId::HistoryPrevious,
            title: "Prompt history previous",
            description: "Select the previous prompt from history",
            category: UiCommandCategory::Prompt,
            keybind: Some("alt+up"),
            include_in_palette: true,
            slash: None,
        },
        UiCommandSpec {
            action_id: UiActionId::HistoryNext,
            title: "Prompt history next",
            description: "Select the next prompt from history",
            category: UiCommandCategory::Prompt,
            keybind: Some("alt+down"),
            include_in_palette: true,
            slash: None,
        },
        UiCommandSpec {
            action_id: UiActionId::PromptStashPush,
            title: "Stash prompt",
            description: "Save the current prompt to stash",
            category: UiCommandCategory::Prompt,
            keybind: None,
            include_in_palette: true,
            slash: None,
        },
        UiCommandSpec {
            action_id: UiActionId::PromptStashList,
            title: "Open prompt stash",
            description: "Open the prompt stash dialog",
            category: UiCommandCategory::Prompt,
            keybind: None,
            include_in_palette: true,
            slash: None,
        },
        UiCommandSpec {
            action_id: UiActionId::PromptSkillList,
            title: "Insert skill command",
            description: "Insert a skill command into the prompt",
            category: UiCommandCategory::Prompt,
            keybind: None,
            include_in_palette: true,
            slash: None,
        },
        UiCommandSpec {
            action_id: UiActionId::CycleVariant,
            title: "Cycle model variant",
            description: "Cycle through available variants for the active model",
            category: UiCommandCategory::Session,
            keybind: Some("ctrl+v"),
            include_in_palette: true,
            slash: None,
        },
        UiCommandSpec {
            action_id: UiActionId::ToggleAppearance,
            title: "Toggle appearance",
            description: "Toggle between light and dark theme variants",
            category: UiCommandCategory::System,
            keybind: None,
            include_in_palette: true,
            slash: None,
        },
        UiCommandSpec {
            action_id: UiActionId::ViewStatus,
            title: "View status",
            description: "Open the status dialog",
            category: UiCommandCategory::System,
            keybind: None,
            include_in_palette: true,
            slash: None,
        },
        UiCommandSpec {
            action_id: UiActionId::ToggleMcp,
            title: "Manage MCP servers",
            description: "Open the MCP management dialog",
            category: UiCommandCategory::System,
            keybind: None,
            include_in_palette: true,
            slash: None,
        },
    ]
}
