// ── Constants & Initial State ───────────────────────────────────────────────
const THEMES = [
  { id: "midnight", label: "Midnight" },
  { id: "graphite", label: "Graphite" },
  { id: "sunset", label: "Sunset" },
  { id: "daylight", label: "Daylight" },
];

const state = {
  sessions: [],
  projects: [],
  providers: [],
  modes: [],
  uiCommands: [],
  selectedProject: null,
  selectedSession: null,
  selectedModel: null,
  selectedModeKey: null,
  selectedTheme: "midnight",
  showThinking: false,
  streaming: false,
  abortRequested: false,
  busyAction: null,
  executionTopology: null,
  recoveryProtocol: null,
  executionRefreshTimer: null,
  promptTokens: 0,
  completionTokens: 0,
  streamMessageNode: null,
  streamReasoningNode: null,
  streamReasoningText: "",
  streamToolBlocks: new Map(),
  streamEventBlocks: new Map(),
  streamStageBlocks: new Map(),
  activeQuestionInteraction: null,
  questionSubmitting: false,
  activePermissionInteraction: null,
  permissionSubmitting: false,
  parentSessionId: null,
};

const nodes = {
  shell: document.getElementById("appShell"),
  sidebarToggle: document.getElementById("sidebarToggle"),
  projectSearch: document.getElementById("projectSearch"),
  projectCount: document.getElementById("projectCount"),
  projectTree: document.getElementById("projectTree"),
  heroPanel: document.getElementById("heroPanel"),
  conversationPanel: document.getElementById("conversationPanel"),
  sessionTitle: document.getElementById("sessionTitle"),
  sessionRuntimeMeta: document.getElementById("sessionRuntimeMeta"),
  sessionMeta: document.getElementById("sessionMeta"),
  executionPanel: document.getElementById("executionPanel"),
  recoveryPanel: document.getElementById("recoveryPanel"),
  stageInspectorPanel: document.getElementById("stageInspectorPanel"),
  messageFeed: document.getElementById("messageFeed"),
  refreshSession: document.getElementById("refreshSession"),
  newSessionBtn: document.getElementById("newSessionBtn"),
  forkSessionBtn: document.getElementById("forkSessionBtn"),
  compactSessionBtn: document.getElementById("compactSessionBtn"),
  renameSessionBtn: document.getElementById("renameSessionBtn"),
  shareSessionBtn: document.getElementById("shareSessionBtn"),
  deleteSessionBtn: document.getElementById("deleteSessionBtn"),
  commandBtn: document.getElementById("commandBtn"),
  commandPanel: document.getElementById("commandPanel"),
  commandClose: document.getElementById("commandClose"),
  commandAbortBtn: document.getElementById("commandAbortBtn"),
  commandRuntimeBadge: document.getElementById("commandRuntimeBadge"),
  commandRuntimeText: document.getElementById("commandRuntimeText"),
  modelSelect: document.getElementById("modelSelect"),
  themeSelect: document.getElementById("themeSelect"),
  agentSelect: document.getElementById("agentSelect"),
  commandSessionNewBtn: document.getElementById("commandSessionNewBtn"),
  commandSessionForkBtn: document.getElementById("commandSessionForkBtn"),
  commandSessionCompactBtn: document.getElementById("commandSessionCompactBtn"),
  commandSessionRenameBtn: document.getElementById("commandSessionRenameBtn"),
  commandSessionShareBtn: document.getElementById("commandSessionShareBtn"),
  commandSessionDeleteBtn: document.getElementById("commandSessionDeleteBtn"),
  commandSessionList: document.getElementById("commandSessionList"),
  commandCatalog: document.getElementById("commandCatalog"),
  questionPanel: document.getElementById("questionPanel"),
  questionPanelTitle: document.getElementById("questionPanelTitle"),
  questionPanelStatus: document.getElementById("questionPanelStatus"),
  questionPanelMeta: document.getElementById("questionPanelMeta"),
  questionClose: document.getElementById("questionClose"),
  questionRejectBtn: document.getElementById("questionRejectBtn"),
  questionForm: document.getElementById("questionForm"),
  questionList: document.getElementById("questionList"),
  questionSubmitBtn: document.getElementById("questionSubmitBtn"),
  permissionPanel: document.getElementById("permissionPanel"),
  permissionPanelTitle: document.getElementById("permissionPanelTitle"),
  permissionPanelStatus: document.getElementById("permissionPanelStatus"),
  permissionPanelMeta: document.getElementById("permissionPanelMeta"),
  permissionClose: document.getElementById("permissionClose"),
  permissionRejectBtn: document.getElementById("permissionRejectBtn"),
  permissionAllowBtn: document.getElementById("permissionAllowBtn"),
  permissionAlwaysBtn: document.getElementById("permissionAlwaysBtn"),
  permissionBody: document.getElementById("permissionBody"),
  composerForm: document.getElementById("composerForm"),
  composerInput: document.getElementById("composerInput"),
  cancelRunBtn: document.getElementById("cancelRunBtn"),
  sendButton: document.getElementById("sendButton"),
  statusBadge: document.getElementById("statusBadge"),
  tokenUsage: document.getElementById("tokenUsage"),
  commandHint: document.getElementById("commandHint"),
  modeBadge: document.getElementById("modeBadge"),
  modelBadge: document.getElementById("modelBadge"),
  directoryBadge: document.getElementById("directoryBadge"),
  heroGreeting: document.getElementById("heroGreeting"),
  chipActions: Array.from(document.querySelectorAll(".hero-chip")),
  overflowToggle: document.getElementById("overflowToggle"),
  overflowMenu: document.getElementById("overflowMenu"),
  settingsToggleBtn: document.getElementById("settingsToggleBtn"),
};
